dist: bionic
group: travis_latest
language: cpp

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++ FUZZ=1 STATIC=1 XERCES3=1 NO_TESTS=1
    - NO_INLINE=1 NO_BIT=1
    - NO_DEBUG=1 NO_TESTS=1
    - SAFETY_PROFILE=1
    - NO_INLINE=1 NO_MULTITOPIC=1 XERCES3=1
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ACE_TAO/ACE
    - TAO_ROOT=$TRAVIS_BUILD_DIR/ACE_TAO/TAO
    - DDS_ROOT=$TRAVIS_BUILD_DIR
    - MPC_ROOT=$TRAVIS_BUILD_DIR/ext/MPC
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$DDS_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-8

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxerces-c-dev
            - g++-8
            - openjdk-8-jdk-headless
      env: COMPILER=g++-8 USE_JAVA=1 NO_DEBUG=1 NO_TESTS=1
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env: COMPILER=clang++ NO_INLINE=1

addons:
  apt:
    packages:
      - libxerces-c-dev
      - libssl-dev
      - g++-8
      - cmake

before_install:
  - mkdir ext
  - cd ext && git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - cd .. && git clone --depth 1 git://github.com/DOCGroup/ACE_TAO.git

branches:
  only:
    - master

before_script:
  - export
  - if [ "$FUZZ" == "1" ]; then
        rm -rf tools/modeling/plugins tools/rapidjson tests/googletest;
        perl $DDS_ROOT/tools/scripts/dds_fuzz.pl;
    fi
  - if [ "$NO_INLINE" == "1" ]; then CONFIG_OPTIONS+=" --no-inline"; fi
  - if [ "$NO_BIT" == "1" ]; then CONFIG_OPTIONS+=" --no-built-in-topics"; fi
  - if [ "$STATIC" == "1" ]; then CONFIG_OPTIONS+=" --static"; fi
  - if [ "$NO_DEBUG" == "1" ]; then CONFIG_OPTIONS+=" --no-debug --optimize"; fi
  - if [ "$SAFETY_PROFILE" == "1" ]; then CONFIG_OPTIONS+=" --safety-profile"; fi
  - if [ "$NO_MULTITOPIC" == "1" ]; then CONFIG_OPTIONS+=" --no-multi-topic"; fi
  - if [ "$USE_JAVA" == "1" ]; then CONFIG_OPTIONS+=" --java"; fi
  - if [ "$NO_TESTS" == "1" ]; then CONFIG_OPTIONS+=" --no-tests"; fi
  - if [ "$USES_WCHAR" == "1" ]; then CONFIG_OPTIONS+=" --features=uses_wchar=1"; fi
  - if [ "$XERCES3" == "1" ]; then CONFIG_OPTIONS+=" --xerces3"; fi
  - if [ "$CXX" == "g++" ]; then CONFIG_OPTIONS+=" --std=c++11"; fi
  - if [ "$VERSIONED_NS" == 1 ]; then CONFIG_OPTIONS+=" --features=versioned_namespace=1"; fi
  - if [ "$DDS_SECURITY" == 1 ]; then CONFIG_OPTIONS+=" --security"; fi
  - ./configure --mpcopts="-workers 4" --compiler=$COMPILER --tests $CONFIG_OPTIONS
  - tools/scripts/show_build_config.pl
  - if [ "$SAFETY_PROFILE" == "1" ]; then
        export LD_LIBRARY_PATH+=:$TRAVIS_BUILD_DIR/build/target/ACE_TAO/ACE/lib:$TRAVIS_BUILD_DIR/build/target/lib;
    fi

script:
  - travis_wait 47 make -s -j 3
  - FILES=$(git clean -nd -e ext); if [ "$FILES" != "" ]; then
        echo ERROR These files should be gitignored;
        echo $FILES;
        exit 1;
    fi
  - if [ "$SAFETY_PROFILE" != "1" ]; then
      $DDS_ROOT/tests/cmake_integration/run_ci_tests.pl;
    fi
  - if [ "$NO_TESTS" == "1" ]; then
      echo Building Messenger;
      $ACE_ROOT/bin/mwc.pl -type gnuace tests/DCPS/Messenger;
      make -C tests/DCPS/Messenger;
    fi
  - if [ "$SAFETY_PROFILE" == "1" ]; then
        cd build/target/tests/DCPS/Messenger && ./run_test.pl rtps_disc;
        cd $DDS_ROOT/build/target/tests/FACE/Messenger;
        ./run_test.pl;
        ./run_test.pl callback;
        ./run_test.pl static;
        ./run_test.pl static callback;
    elif [ "$USE_JAVA" == "1" ]; then
        cd java/tests/messenger;
        ./run_test.pl tcp;
        ./run_test.pl rtps;
    else
        cd tests/DCPS/Messenger && ./run_test.pl all;
    fi
