sudo: false
language: cpp

compiler:
  - gcc

env:
  matrix:
    - FUZZ=1 STATIC=1 XERCES3=1 NO_TESTS=1
    - NO_INLINE=1 NO_BIT=1
    - NO_INLINE=1
    - NO_DEBUG=1 NO_TESTS=1
    - SAFETY_PROFILE=1
    - NO_INLINE=1 USES_WCHAR=1
    - NO_INLINE=1 NO_MULTITOPIC=1 XERCES3=1
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ACE_TAO/ACE
    - TAO_ROOT=$TRAVIS_BUILD_DIR/ACE_TAO/TAO
    - DDS_ROOT=$TRAVIS_BUILD_DIR
    - MPC_ROOT=$TRAVIS_BUILD_DIR/ext/MPC
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$DDS_ROOT/lib:$LD_LIBRARY_PATH
    - COMPILER=g++-7

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxerces-c-dev
            - g++-6
            - openjdk-7-jdk
      env: USE_JAVA=1 NO_DEBUG=1 NO_TESTS=1 COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - libxerces-c-dev
            - clang++-5.0
      env: COMPILER=clang++-5.0
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: COMPILER=clang++ NO_INLINE=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libxerces-c-dev
      - g++-7

before_install:
  - mkdir ext
  - cd ext && git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - cd .. && git clone --depth 1 git://github.com/DOCGroup/ACE_TAO.git

branches:
  only:
    - master

before_script:
  - export
  - if [ "$FUZZ" == "1" ]; then
        rm -rf tools/modeling/plugins tools/IntermediateTypeLang/cpp/rapidjson;
        perl $DDS_ROOT/tools/scripts/dds_fuzz.pl;
    fi
  - if [ "$NO_INLINE" == "1" ]; then CONFIG_OPTIONS+=" --no-inline"; fi
  - if [ "$NO_BIT" == "1" ]; then CONFIG_OPTIONS+=" --no-built-in-topics"; fi
  - if [ "$STATIC" == "1" ]; then CONFIG_OPTIONS+=" --static"; fi
  - if [ "$NO_DEBUG" == "1" ]; then CONFIG_OPTIONS+=" --no-debug --optimize"; fi
  - if [ "$SAFETY_PROFILE" == "1" ]; then CONFIG_OPTIONS+=" --safety-profile"; fi
  - if [ "$NO_MULTITOPIC" == "1" ]; then CONFIG_OPTIONS+=" --no-multi-topic"; fi
  - if [ "$USE_JAVA" == "1" ]; then CONFIG_OPTIONS+=" --java"; fi
  - if [ "$NO_TESTS" == "1" ]; then CONFIG_OPTIONS+=" --no-tests"; fi
  - if [ "$USES_WCHAR" == "1" ]; then CONFIG_OPTIONS+=" --features=uses_wchar=1"; fi
  - if [ "$XERCES3" == "1" ]; then CONFIG_OPTIONS+=" --xerces3"; fi
  - if [ "$CXX" == "g++" ]; then CONFIG_OPTIONS+=" --macros=c++11=1"; fi
  - ./configure --mpcopts="-workers 2" --compiler=$COMPILER $CONFIG_OPTIONS
  - tools/scripts/show_build_config.pl
  - if [ "$SAFETY_PROFILE" == "1" ]; then
        export LD_LIBRARY_PATH+=:$TRAVIS_BUILD_DIR/build/target/ACE_TAO/ACE/lib:$TRAVIS_BUILD_DIR/build/target/lib;
    fi

script:
  - travis_wait 45 make -s -j 6
  - if [ "$SAFETY_PROFILE" == "1" ]; then
        cd build/target/tests/DCPS/Messenger && ./run_test.pl rtps_disc;
        cd $DDS_ROOT/build/target/tests/FACE/Messenger;
        ./run_test.pl;
        ./run_test.pl callback;
        ./run_test.pl static;
        ./run_test.pl static callback;
    elif [ "$USE_JAVA" == "1" ]; then
        cd java/tests/messenger;
        ./run_test.pl tcp;
        ./run_test.pl rtps;
    else
        cd tests/DCPS/Messenger && ./run_test.pl all;
    fi
