# Site settings
title: OpenDDS
email: info@opendds.org
description: OpenDDS is an open source C++ implementation of the Object Management Group (OMG) Data Distribution Service (DDS). OpenDDS also supports Java bindings through JNI.
twitter_username: OpenDDS
github_username:  objectcomputing

theme: minima

# github-metadata
repository: objectcomputing/OpenDDS
plugins: ['jekyll-github-metadata', 'jekyll-redirect-from']

liquid:
  error_mode: strict

exclude:
  - README.md
