branches:
  only:
    - master

install:
  - mkdir ext && cd ext
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone -q -b Latest_Beta --depth 1 git://github.com/DOCGroup/ATCD.git
  - cd ..
  - set MPC_ROOT=%CD%\ext\MPC
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - call configure --no-tests --ace=ext\ATCD\ACE

platform:
  - x64

configuration:
  - Debug

build:
  parallel: true
  project: DDS_TAOv2.sln

after_build:
  - cd DevGuideExamples\DCPS\Messenger && appveyor_run_test.pl
  - cd ..\..\..\tests\DCPS\Messenger && run_test.pl

test: off
