name: "Insert PR Number into News"

on:
  pull_request:
    paths:
      - 'docs/news.d/**'
    types: [opened, synchronize]

jobs:
  insert_news_pr_num:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenDDS
      uses: actions/checkout@v3
    - name: Checkout PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh pr checkout ${{ github.event.pull_request.number }}
    - name: Update PR
      run: python3 docs/news.py insert-pr-num ${{github.event.pull_request.number}}
