name: Sphinx Tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'workflows/**'
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'

jobs:
  strict:
    runs-on: ubuntu-latest
    steps:
    - name: checkout OpenDDS
      uses: actions/checkout@v6

    - name: Run Strict Checks
      run: |
        python3 docs/build.py strict

  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: checkout OpenDDS
      uses: actions/checkout@v6

    - name: Run Link Checks
      run: |
        python3 docs/build.py linkcheck
